#!/bin/sh
# Program to make Guile interface to TeXmacs

# This must be enabled to make this work right with Guile 2.
GUILE_AUTO_COMPILE=fresh
export GUILE_AUTO_COMPILE

# update documentation of glue 
guile -l make-apidoc-module.scm  -c "(quit)" 2>/dev/null | cat > ../../../TeXmacs/progs/prog/glue-symbols.scm

guile -l make-apidoc-doc.scm  -c "(quit)" 2>/dev/null | cat > ../../../TeXmacs/doc/devel/scheme/api/glue-auto-doc.en.tm

