#!/bin/sh
case "$1" in
    1.8)
        sudo apt-get install guile-1.8-dev
    ;;
    2.0)
        sudo apt-get install guile-2.0-dev
    ;;
    2.2)
        sudo dpkg -r guile-1.8-dev guile-2.0-dev
        sudo dpkg -i ../../../Guile/guile-2.2-dev_2.1.3-git-1_amd64.deb
    ;;
esac

echo Run: sudo -k  by hand if done with root access.
