#!/bin/sh
case "$1" in
    1.8)
        sudo apt-get install guile-1.8-dev
    ;;
    2.0)
        sudo apt-get install guile-2.0-dev
    ;;
    2.2)
        PACKAGE=$(ls -v ~/src/Guile/guile-2.2-dev_*_amd64.deb | tail -n 1)
        sudo dpkg -r guile-1.8-dev guile-2.0-dev
        sudo dpkg -i "${PACKAGE}"
    ;;
esac

echo
echo Run: sudo -k  by hand if you are finished with root access.
echo
